

- name: Install k8s and docker packages
  become: yes
  remote_user: ec2-user
  become: yes
  hosts: tag_Infra_K8S
  roles:
    - all

- name: Setup master node
  become: yes
  remote_user: ec2-user
  become: yes
  hosts: tag_Type_MASTER
  roles:
    - master


- name: Setup worker node
  become: yes
  remote_user: ec2-user
  become: yes
  hosts: tag_Type_WORKER
  roles:
    - workers